[mgr]
sort_by        = "natural"
sort_reverse 	 = false
# [plugin]
# prepend_preloaders = [
#   # Do not preload files in mounted locations:
#   # Environment variable won't work here.
#   # Using absolute path instead.
#   { name = "/run/user/1000/gvfs/**/*", run = "noop" },
#
#   # For mounted hard disk/drive
#   { name = "/run/media/USER_NAME/**/*", run = "noop" },
# ]
# prepend_previewers = [
#   # Allow to preview folder.
#   { name = "*/", run = "folder" },
#
#   # Do not previewing files in mounted locations.
#   # Uncomment the line below to allow previewing text files.
#   # { mime = "{text/*,application/x-subrip}", run = "code" },
#
#   # Using absolute path.
#   { name = "/run/user/1000/gvfs/**/*", run = "noop" },
#
#   # For mounted hard disk/drive.
#   { name = "/run/media/USER_NAME/**/*", run = "noop" },
# ]
[opener]

edit = [
  { run = 'nvim "$@"', block = true, desc = "Neovim-in-curr" },
]
