#!/bin/bash
args=("$@")
for ((i=0; i<${#args[@]}; i++)); do
    if [[ "${args[i]}" == "socket_input" || "${args[i]}" == "socket_output" ]]; then
        socket_name="${args[i+1]}"
        if [ -S "/tmp/$socket_name" ]; then
            chmod 777 "/tmp/$socket_name" 2>/dev/null
        fi
    fi
done

ANDROID_DATA=/data \
ANDROID_ROOT=/system \
PATH=/system/bin:/system/xbin:$PATH \
LD_LIBRARY_PATH=/system/lib64:/system/lib:/vendor/lib64:/vendor/lib:/odm/lib64:/odm/lib \
/system/bin/am "$@"
