## AUTOSTART ##
# ai
exec-once = /usr/bin/firefox --name=ai-browser -P hminimal2 --new-instance gemini.google.com --new-window  gemini.google.com  --new-window gemini.google.com

## WINDOW-RULES ##

# AI Browser
windowrule {
    name = ai-browser
    match:class = (ai-browser)
    workspace = 5 silent
}

# Cheat
windowrule {
    name = cheat
    match:class = (cheat)
    float = true
    move = (monitor_w-window_w-100) 66
    pin = true
    size = 300 400
    no_initial_focus = true
    rounding = 0
    border_size = 0
    no_shadow = true
    no_blur = true
}
source = ~/Water/crap/scripts/windowrule_cheat.conf 

# Notifi
windowrule {
    name = noti
    match:class = (noti)
    float = true
    move = (monitor_w-window_w-16) 66
    pin = true
    size = 300 400
    no_initial_focus = true
}
#oldformat
## ai-browser 
#windowrule = workspace 5 silent, class:^(ai-browser)$
#
##cheat
#windowrulev2 = noborder, class:^(cheat)$
#windowrulev2 = noshadow, class:^(cheat)$
#windowrulev2 = norounding, class:^(cheat)$
#windowrulev2 = noblur, class:^(cheat)$
##windowrulev2 = opacity 1.0 override 1.0 override, class:^(cheat)$
#windowrule = float,class:(cheat)
#windowrule = move 100%-w-100 66,class:(cheat) 
#windowrule = pin, class:(cheat)
#windowrule = size 300 400,class:(cheat)
#windowrulev2 = noinitialfocus, class:(cheat)
#source = ~/Water/crap/scripts/windowrule_cheat.conf 
#
#
#
## notifi 
#windowrule = float,class:(noti)
#windowrule = move 100%-w-16 66,class:(noti) 
#windowrule = pin, class:(noti)
#windowrule = size 300 400,class:(noti)
#windowrulev2 = noinitialfocus, class:(noti)

#misc {
#   # Set to 1 (always on) or 0 (always off)
#   # Try '1' first if your monitor supports it well.
#   vrr = 1
#}
# applying any'one' is equivalent to fakefullscreen for firefox i.e it keeps the search bar intact even in full screen
# about:config browser.fullscreen.autohide false
# windowrulev2 = syncfullscreen 0, class:^(firefox)$
