# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
[mgr]

prepend_keymap = [
  # goto
	{ on = [ "g", "f" ],       run = "cd /sdcard/Documents/Fire/", desc = "go to fire" },
	{ on = [ "g", "w" ],       run = "cd ~/Water",       desc = "go to water" },
	{ on = [ "g", "i" ],       run = "cd ~/Water/crap",       desc = "go to crap" },
	{ on = [ "g", "y" ],       run = "cd ~/.config/yazi",       desc = "go to yazi" },
	{ on = [ "g", "D" ],       run = "cd ~/Downloads",       desc = "go to crap" },
	{ on = [ "g", "d" ],       run = "cd ~/Water/crap/dotfiles/",       desc = "go to nvim" },
	{ on = [ "g", "F" ],       run = "follow",           desc = "Follow hovered symlink" },
	{ on = [ "g", "n" ],       run = "cd ~/.config/nvim",       desc = "go to nvim" },
	{ on = [ "g", "s" ],       run = "cd /sdcard",       desc = "go to sdcard" },
	{ on = [ "g", "t" ],       run = "cd /termux/home/",       desc = "go to termux" },

	# Operation
	{ on = "<S-Enter>", run = "shell --block -- nvim %s", desc = "Open selected files interactively" },
	{on  = "<C-n>" , run = 'shell -- dragon-drop -x -i -T "$0"' , desc = "drag and drop"},

	# yamb bookmarks
	{ on = [ "u", "a" ], run = "plugin yamb -- save", desc = "Add bookmark" },
	{ on = [ "u", "g" ], run = "plugin yamb -- jump_by_key", desc = "Jump bookmark by key" },
	{ on = [ "u", "j" ], run = "plugin yamb -- jump_by_fzf", desc = "Jump bookmark by fzf" },
	{ on = [ "u", "d" ], run = "plugin yamb -- delete_by_key", desc = "Delete bookmark by key" },
	{ on = [ "u", "D" ], run = "plugin yamb -- delete_by_fzf", desc = "Delete bookmark by fzf" },
	{ on = [ "u", "A" ], run = "plugin yamb -- delete_all", desc = "Delete all bookmarks" },
	{ on = [ "u", "r" ], run = "plugin yamb -- rename_by_key", desc = "Rename bookmark by key" },
	{ on = [ "u", "R" ], run = "plugin yamb -- rename_by_fzf", desc = "Rename bookmark by fzf" },
]
