[mgr]
sort_by        = "natural"
sort_reverse 	 = false
[opener]

edit = [
  { run = 'kitty -e nvim "$@" > /dev/null 2>&1 &', block = true, desc = "Neovim" },
  { run = 'nvim "$@"', block = true, desc = "Neovim-in-curr" },
]
