## Storage array paths
EFI1_PATH="/home/ixdire/efi1"
EFI2_PATH="/home/ixdire/efi2"
ARRAY_PARTITION="/dev/nvme0n1p5"
MD_DEVICE="/dev/md0"
## Hugepages amount
# 8388608 KiB (8GB) = 4096 pages of 2048kB
HUGEPAGES_AMOUNT=9500
